[package]
name = "v5_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.5", features = [
	"derive",
	"cargo",
	"unicode",
	"std",
	"suggestions",
], default_features = false }
clap-num = "1.0.0"
lazy_static = "1.4.0"
log = "0.4.14"
phf = { version = "0.10", features = ["macros"] }
png = "0.17.2"
rand = "0.8.4"
v5_device = { path = "../lib" }
