[package]
name = "reveng-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^3.0.0-rc.8", features = [
	"derive",
	"cargo",
	"unicode",
	"std",
	"suggestions",
], default_features = false }
env_logger = "0.9.0"
log = "0.4.14"
speedy = "^0.8.0"
speedy-derive = "^0.8.0"

[features]
